name: Generate ⭢ auth-service

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    paths:
      - 'protos/auth-service/**'

jobs:
  generate-csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Bump version
        id: versioning
        uses: nsmolianitski/semver-action@v0.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
      - uses: baboon-co/iron-forge-contracts/.github/workflows/generate-csharp.yml@master
        with:
          service: auth-service
          version: ${{ steps.versioning.outputs.new_version }}
