name: Generate ⭢ auth-service

on:
  workflow_dispatch:
  push:
    paths:
      - 'protos/auth-service/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: versioning
        uses: nsmolianitski/semver-action@v0.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  generate-csharp:
    needs: bump-version
    uses: ./.github/workflows/generate-csharp.yml
    with:
      service: auth-service
      version: ${{ needs.bump-version.outputs.version }}
