name: Generate ⭢ auth-service

on:
  workflow_dispatch:
  push:
    paths:
      - 'protos/AuthService/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versioning.outputs.new_version_raw }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: versioning
        uses: nsmolianitski/semver-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_name: auth-service

  generate-csharp:
    needs: bump-version
    uses: ./.github/workflows/generate-csharp.yml
    with:
      service: AuthService
      version: ${{ needs.bump-version.outputs.version }}
